### ISSUE TITLE
python3: TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by nil0x42** [0x00-0x00/ShellPop#29]
ShellPop is incompatible with python3 due to inentation error in ./bin/shellpop.

```$ python3 bin/shellpop```
```py
  File "bin/shellpop", line 811
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by 0x00-0x00** [comment]
Hey @nil0x42! Thanks for reporting this issue.

Yes, I am aware that Shellpop is not Python3 compatible, it is written in README.md

![image](https://user-images.githubusercontent.com/23364530/50778213-23f4c800-127c-11e9-8ecd-9ec4fd544399.png)

This was a decision I have made purely because python2 is easier to code and would require a major refactoring to comply everything to the newer version, plus, don't know if all dependencies are going to work.

Again, thanks for caring for this project, I am deeply grateful.
